on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
      
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - uses: actions/checkout@v2
    
    - name: mobsfscan
      uses: MobSF/mobsfscan@main
      with:
        args: '. -x --version --sonarqube --output results.json || true'
        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
            args: >
              -Dsonar.organization=frik0
              -Dsonar.projectKey=frik0_Hello-World-iOS
              -Dsonar.verbose=true
              -Dsonar.externalIssuesReportPaths=results.json
